// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcvfjipbeuiyaegblsit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjdmZqaXBiZXVpeWFlZ2Jsc2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjQzMjUsImV4cCI6MjA2NTE0MDMyNX0.ti99NhjAS2K5dUHPjLTMMFOTkAMeF4cdIruZnz-W2yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);